from pathlib import Path

path = Path('src/main.jsx')
text = path.read_text(encoding='utf-8')

old_readiness = '''function operationReadiness(op,data){\n  const players=(data.players||[]).filter(p=>p.memberUserId||p.id);\n  const attendance=op?.attendanceByPlayer||{};\n  const going=players.filter(p=>attendance[p.id]==='going');\n  const responded=players.filter(p=>attendance[p.id]);\n  const squads=op?.squads||[];\n  const assignedIds=new Set(squads.flatMap(s=>s.playerIds||[]));\n  const phases=op?.strategyData?.phases||[];\n  const maps=op?.stageMaps||[];\n  const briefs=op?.briefingsByPlayer||{};\n  const checks=[\n    {key:'attendance',label:'PLAYER READINESS',detail:`${responded.length}/${players.length} responded`,ok:players.length>0&&responded.length===players.length},\n    {key:'squads',label:'SQUAD ASSIGNMENT',detail:`${going.filter(p=>assignedIds.has(p.id)).length}/${going.length||0} going players assigned`,ok:going.length>0&&going.every(p=>assignedIds.has(p.id))},\n    {key:'strategy',label:'STRATEGY',detail:`${phases.filter(p=>p.intent&&p.tasks?.length).length}/${phases.length||4} phases ready`,ok:!!op?.strategyData?.intent&&!!op?.strategyData?.orders&&phases.length>=4&&phases.every(p=>p.intent&&p.tasks?.length)},\n    {key:'maps',label:'STAGE MAPS',detail:`${maps.filter(m=>(m.markers||[]).length).length}/${maps.length||4} phases mapped`,ok:maps.length>=4&&maps.every(m=>(m.markers||[]).length>0)},\n    {key:'briefings',label:'BRIEFINGS',detail:`${going.filter(p=>briefs[p.id]?.published).length}/${going.length||0} published`,ok:going.length>0&&going.every(p=>briefs[p.id]?.published)}\n  ];\n  const ready=checks.filter(c=>c.ok).length;\n  return {checks,percent:Math.round((ready/checks.length)*100)};\n}'''

new_readiness = '''function operationReadiness(op,data){\n  const players=(data.players||[]).filter(p=>p.memberUserId||p.id);\n  const attendance=op?.attendanceByPlayer||{};\n  const going=players.filter(p=>attendance[p.id]==='going');\n  const responded=players.filter(p=>attendance[p.id]);\n  const squads=op?.squads||[];\n  const assignedIds=new Set(squads.flatMap(s=>s.playerIds||[]));\n  const assignedGoing=going.filter(p=>assignedIds.has(p.id));\n  const phases=op?.strategyData?.phases||[];\n  const maps=op?.stageMaps||[];\n  const briefs=op?.briefingsByPlayer||{};\n  const activeSquads=squads.filter(s=>(s.playerIds||[]).some(pid=>going.some(p=>p.id===pid)));\n  const coveredSquads=activeSquads.filter(s=>{\n    const lead=players.find(p=>p.id===s.lead||p.memberUserId===s.lead||p.name===s.lead);\n    return !!lead && ['commander','co','squad_lead'].includes(lead.accessRole||lead.role);\n  });\n  const checks=[\n    {key:'attendance',label:'PLAYER READINESS',detail:`${responded.length}/${players.length} responded`,ok:players.length>0&&responded.length===players.length},\n    {key:'squads',label:'SQUAD ASSIGNMENT',detail:`${assignedGoing.length}/${going.length||0} going players assigned`,ok:going.length>0&&going.every(p=>assignedIds.has(p.id))},\n    {key:'leadership',label:'SQUAD LEAD COVERAGE',detail:`${coveredSquads.length}/${activeSquads.length||0} active squads have command coverage`,ok:activeSquads.length>0&&coveredSquads.length===activeSquads.length},\n    {key:'strategy',label:'STRATEGY',detail:`${phases.filter(p=>p.intent&&p.tasks?.length).length}/${phases.length||4} phases ready`,ok:!!op?.strategyData?.intent&&!!op?.strategyData?.orders&&phases.length>=4&&phases.every(p=>p.intent&&p.tasks?.length)},\n    {key:'maps',label:'STAGE MAPS',detail:`${maps.filter(m=>(m.markers||[]).length).length}/${maps.length||4} phases mapped`,ok:maps.length>=4&&maps.every(m=>(m.markers||[]).length>0)},\n    {key:'briefings',label:'BRIEFINGS',detail:`${going.filter(p=>briefs[p.id]?.published).length}/${going.length||0} published`,ok:going.length>0&&going.every(p=>briefs[p.id]?.published)}\n  ];\n  const ready=checks.filter(c=>c.ok).length;\n  return {checks,percent:Math.round((ready/checks.length)*100)};\n}'''

if old_readiness not in text:
    raise SystemExit('readiness block not found')
text = text.replace(old_readiness, new_readiness, 1)

old_detail = '''function OperationDetail({data,setData,user,clan}){\n  const {id}=useParams(); const navigate=useNavigate();\n  const op=data.ops.find(x=>x.id===id);\n  const [tab,setTab]=useState('overview');\n  const command=canCommand(clan); const squadManager=canManageSquads(clan);\n  if(!op) return <div className="card"><h2>Operation not found</h2><button className="btn" onClick={()=>navigate('/operations')}><ArrowLeft size={15}/> BACK</button></div>;\n  const update=(patch)=>setData(d=>({...d,ops:d.ops.map(x=>x.id===op.id?{...x,...patch}:x)}));\n  const nested=()=>{setData(d=>({...d,ops:d.ops.map(x=>x.id===op.id?makeOperation(x):x)}))};\n  const attendanceValues=Object.values(op.attendanceByPlayer||{}); const going=attendanceValues.filter(v=>v==='going').length; const responded=attendanceValues.length;\n  const playersWithIds=data.players.filter(p=>p.memberUserId||p.id);\n  return <>\n    <PageHead eyebrow={`OPERATION #${op.id}`} title={op.name} subtitle={`${op.map} · ${op.mode} · ${op.date} · ${op.time} · VS ${op.opponent}`} actions={<><Tag tone={op.status==='active'?'green':op.status==='archived'?'':'yellow'}>{op.status.toUpperCase()}</Tag>{command&&<button className="btn" onClick={()=>update({status:op.status==='draft'?'active':op.status==='active'?'archived':'draft'})}>{op.status==='draft'?'ACTIVATE':op.status==='active'?'ARCHIVE':'REOPEN'}</button>}<button className="btn" onClick={()=>navigate('/operations')}><ArrowLeft size={15}/> BACK</button></>}/>'''

new_detail = '''function OperationDetail({data,setData,user,clan}){\n  const {id}=useParams(); const navigate=useNavigate();\n  const op=data.ops.find(x=>x.id===id);\n  const [tab,setTab]=useState('overview');\n  const command=canCommand(clan); const squadManager=canManageSquads(clan);\n  if(!op) return <div className="card"><h2>Operation not found</h2><button className="btn" onClick={()=>navigate('/operations')}><ArrowLeft size={15}/> BACK</button></div>;\n  const readiness=operationReadiness(op,data);\n  const update=(patch)=>setData(d=>({...d,ops:d.ops.map(x=>x.id===op.id?{...x,...patch}:x)}));\n  const transition=()=>{\n    if(op.status==='draft'){ if(readiness.percent===100) update({status:'ready'}); return; }\n    if(op.status==='ready'){ update({status:'active'}); return; }\n    if(op.status==='active'){ update({status:'archived'}); return; }\n    update({status:'draft'});\n  };\n  const actionLabel=op.status==='draft'?(readiness.percent===100?'MARK READY':'READINESS CHECK'):op.status==='ready'?'ACTIVATE':op.status==='active'?'ARCHIVE':'REOPEN DRAFT';\n  const nested=()=>{setData(d=>({...d,ops:d.ops.map(x=>x.id===op.id?makeOperation(x):x)}))};\n  const attendanceValues=Object.values(op.attendanceByPlayer||{}); const going=attendanceValues.filter(v=>v==='going').length; const responded=attendanceValues.length;\n  const playersWithIds=data.players.filter(p=>p.memberUserId||p.id);\n  return <>\n    <PageHead eyebrow={`OPERATION #${op.id}`} title={op.name} subtitle={`${op.map} · ${op.mode} · ${op.date} · ${op.time} · VS ${op.opponent}`} actions={<><Tag tone={op.status==='active'?'green':op.status==='ready'?'green':op.status==='archived'?'':'yellow'}>{op.status.toUpperCase()}</Tag>{command&&<button className="btn" onClick={transition} disabled={op.status==='draft'&&readiness.percent<100}>{actionLabel}</button>}<button className="btn" onClick={()=>navigate('/operations')}><ArrowLeft size={15}/> BACK</button></>}/>'''

if old_detail not in text:
    raise SystemExit('detail block not found')
text = text.replace(old_detail, new_detail, 1)

old_readiness_component = '''    {command && op.status==='draft' && <div className="readiness-footer"><div><b>{r.percent===100?'All deployment gates are green.':'Finish the pending gates before launch.'}</b><small>Activation remains manual; readiness is your command safety check.</small></div><button className="btn primary" onClick={onActivate}><Radio size={15}/> ACTIVATE OPERATION</button></div>}'''
new_readiness_component = '''    {command && op.status==='draft' && <div className="readiness-footer"><div><b>{r.percent===100?'All readiness gates are green.':'Finish the pending gates before marking Ready.'}</b><small>The lifecycle is manual: Draft → Ready → Active → Archived.</small></div><button className="btn primary" onClick={onActivate} disabled={r.percent<100}><Radio size={15}/> {r.percent===100?'MARK READY':'READINESS PENDING'}</button></div>}\n    {command && op.status==='ready' && <div className="readiness-footer"><div><b>Operation is Ready for deployment.</b><small>All readiness checks are green. Activation is still a deliberate command action.</small></div><button className="btn primary" onClick={onActivate}><Radio size={15}/> ACTIVATE OPERATION</button></div>}'''

if old_readiness_component not in text:
    raise SystemExit('readiness component block not found')
text = text.replace(old_readiness_component, new_readiness_component, 1)

old_onactivate = '''<OperationReadiness op={op} data={data} command={command} onActivate={()=>update({status:'active'})}/>'''
new_onactivate = '''<OperationReadiness op={op} data={data} command={command} onActivate={()=>update({status:op.status==='draft'?'ready':op.status==='ready'?'active':op.status})}/>'''
if old_onactivate not in text:
    raise SystemExit('onActivate usage not found')
text = text.replace(old_onactivate, new_onactivate, 1)

old_status = '''<td>{op.status==='active'?<Tag tone="green">ACTIVE</Tag>:op.status==='draft'?<Tag tone="yellow">DRAFT</Tag>:<Tag>ARCHIVED</Tag>}</td>'''
new_status = '''<td>{op.status==='active'?<Tag tone="green">ACTIVE</Tag>:op.status==='ready'?<Tag tone="green">READY</Tag>:op.status==='draft'?<Tag tone="yellow">DRAFT</Tag>:<Tag>ARCHIVED</Tag>}</td>'''
if old_status in text:
    text = text.replace(old_status, new_status, 1)

path.write_text(text, encoding='utf-8')
print('production_patch applied')

# release-trigger: 2026-09-16
